# Generated by Django 4.0 on 2024-11-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='comment',
            new_name='article',
        ),
    ]
